class Form {
constructor (){
this.title=createElement('h1',"Health is Wealth!!!")
this.test=createButton("Test for covid-19")
this.about=createButton("Boosting Immunity")
this.immunity1=createElement('h1',"Immunity boosting ways:")
this.immunity2=createElement('h3',"1. Drink warm water with 1/2tbsp turmeric and 1/2tbsp lemon every early morning")
this.immunity3=createElement('h3',"2.If you have a normal cough you can make a remedy for it:")
this.immunity4=createElement('h2',"'Take some honey in bowl and put 1 tbsp of ginger powder in it , mix well and eat it daily till your cough dosent recover'")
this.immunity5=createElement('h3',"3.Eat clove")
this.immunity6=createElement('h3',"4.Eat healthy green vegetables.")
this.back=createButton('Back')
this.back.hide()

this.positive=createElement('h3',"your infection is high, we recommend you to self-quarantine yourself")
this.negative=createElement('h3',"Your infection risk is low we recommend you to stay at home to avoid any chance of exposure to novel corona virus.")
this.immunity1.hide()
this.immunity2.hide()
this.immunity3.hide()
this.immunity4.hide()
this.immunity5.hide()
this.immunity6.hide()
this.positive.hide()
this.negative.hide()
this.q1=createElement('h2',"Q1.Are you experiencing any of the following symptoms?")
this.q1.hide()
this.r1=createRadio('h2')
this.r1.option("Cough")
this.r1.option("Fever")
this.r1.option("Difficulty in breathing")
this.r1.option("Loss of smell/taste")
this.r1.option("None of these")
this.r1.hide()
//this.r1.style('height','25px')
//this.r1.style('position','absolute')
this.q2=createElement('h2',"2.Have you ever had any of these:")
this.q2.hide()

this.r2=createRadio('h2')
this.r2.option("Diabetes")
this.r2.option("hypertension")
this.r2.option("Lung Disease")
this.r2.option("Hear Disease")
this.r2.option("Kidney Disorder")
this.r2.option("None of these")
this.r2.hide()
this.q3=createElement('h2',"3.Have you travelled anywhere internationally in last 28-45 days?")
this.q3.hide()
this.r3=createRadio('h2')
this.r3.option("yes")
this.r3.option("No")
this.r3.hide()
this.q4=createElement('h2',"which of these will apply to you?")
this.q4.hide()
this.r4=createRadio('h2')
this.r4.option("I Have recenty interacted or lived with someone who has tested positive for COVID-19")
this.r4.option("I am a healthcare worker and I have Recently examined a COVID-19 confirmed case without protective gears")
this.r4.option("None of these")
this.r4.hide()
this.result=createButton("see the result")
this.result.hide()
this.l= createA('https://www.mygov.in/covid-19','covid updates','_blank')
}
display(){
//image(bg,displayWidth,displayHeight,displayWidth,displayHeight)
this.title.position(displayWidth/2-150,100)
this.test.position(displayWidth/2-200,300)
this.about.position(displayWidth/2,300)
this.l.position(displayWidth/2-80,400)

this.test.mousePressed(()=>{

this.q1.show()
this.q2.show()
this.q3.show()
this.q4.show()
this.r1.show()
this.r2.show()
this.r3.show()
this.r4.show()
this.result.show()
this.title.hide()
this.test.hide()
this.about.hide()
this.back.show()
this.l.hide()
this.q1.position(displayWidth/2-400,40)
this.r1.position(displayWidth/2-400,100)
this.q2.position(displayWidth/2-400,140)
this.r2.position(displayWidth/2-400,200)
this.q3.position(displayWidth/2-400,240)
this.r3.position(displayWidth/2-400,300)
this.q4.position(displayWidth/2-400,340)
this.r4.position(displayWidth/2-400,400)
this.result.position(displayWidth/2-170,520)
this.back.position(displayWidth-100,50)

})
this.result.mousePressed(()=>{
    var ans1 =this.r1.value()
var ans2=this.r2.value()
var ans3 =this.r3.value()
var ans4=this.r4.value()
console.log(ans1)
if(ans1==="None of these" && ans2==="None of these" && ans3==="No" && ans4==="None of these") 
{
c=1
}
    this.q1.hide()
    this.r1.hide()
    this.q2.hide()
    this.r2.hide()
    this.q3.hide()
    this.r3.hide()
    this.q4.hide()
    this.r4.hide()
    this.result.hide()
    if(c===1){
        //text("Your infection risk is low we recommend you to stay at home to avoid any chancdise of exposure to novel corona virus.",playWidth/2-500,300)
   this.negative.show()
   this.negative.position(displayWidth/2-500,300)
   
      }

    else{
        //text("your infection is high, we recommend you to self-quarantine yourself",displayWidth/2-100,300)
    this.positive.show()
      this.positive.position(displayWidth/2-200,300)
    
      }
    })   
  this.about.mousePressed(()=>{
    this.title.hide()
    this.test.hide()
    this.about.hide()
    this.l.hide()
    this.immunity1.show()
    this.immunity1.position(displayWidth/2-500,150)
    this.immunity2.show()
    this.immunity2.position(displayWidth/2-500,200)
    this.immunity3.show()
    this.immunity3.position(displayWidth/2-500,250)
    this.immunity4.show()
    this.immunity4.position(displayWidth/2-500,350)
    this.immunity5.show()
    this.immunity5.position(displayWidth/2-500,450)
    this.immunity6.show()
    this.immunity6.position(displayWidth/2-500,500)
    this.back.show()
    this.back.position(displayWidth-100,50)

   // textSize(20)
  //text("Immunity boosting ways:\n\n 1. Drink warm water with 1/2tbsp turmeric and 1/2tbsp lemon every early morning .\n\n 2. If you have a normal cough you can make a remedy for it:\n\nTake some honey in bowl and put 1 tbsp of ginger powder in it , mix well and eat it daily till your cough dosent recover.\n\n3. Eat clove\n\n 4.Eat healthy green vegetables.",displayWidth/2-500,200)
  })

   this.back.mousePressed(()=>{
    this.title.show()
    this.test.show()
    this.about.show()
    this.result.hide()
    this.l.show()
    c=0
    this.immunity1.hide()
    this.immunity2.hide()
    this.immunity3.hide()
    this.immunity4.hide()
    this.immunity5.hide()
    this.immunity6.hide()
    this.q1.hide()
    this.q2.hide()
    this.q3.hide()
    this.q4.hide()
    this.r1.hide()
    this.r2.hide()
    this.r3.hide()
    this.r4.hide()
    this.negative.hide()
    this.positive.hide()
    this.back.hide()
    
   })
 
}


}